/** Anime source enum. */
export enum AnimeSource {
  FourKomaManga = 'FOUR KOMA MANGA',
  Book = 'BOOK',
  CardGame = 'CARD GAME',
  Game = 'Game',
  LightNovel = 'LIGHT NOVEL',
  Manga = 'MANGA',
  MixedMedia = 'MIXED MEDIA',
  Music = 'MUSIC',
  Novel = 'NOVEL',
  Original = 'ORIGINAL',
  PictureBook = 'PICTURE BOOK',
  Radio = 'RADIO',
  VisualNovel = 'VISUAL NOVEL',
  WebManga = 'WEB MANGA',
  WebNovel = 'WEB NOVEL',
  Other = 'OTHER',
  Unknown = 'UNKNOWN',
}
